## -------------- project specific parameters to be changed -------------- ##

# the sample name should be the SAN
# the SAN needs to be written exactly as it appears in sample manager
# because it used to look up information on the sample
# including with the correct number of zeros
# ie., 21-02023-0001 will work but 21-02023-01 will not work

# Example samples and paths are below
# Change these to your particular samples

samples:
  21-02023-0003:
    - ../introduction/raw_data/21-02023-03_S6_L001_R1_001.fastq.gz
    - ../introduction/raw_data/21-02023-03_S6_L001_R2_001.fastq.gz



## -------------- pipeline parameters -------------- ##

# -------------- Trimming -------------- #

# Trimmomatic is used for trimming the Illumina reads
# The program requires an adapter file specific for the sequencing run
# and a minimum quality score can be given

trimmomatic_adapters: "NexteraPE-PE.fa"
trimmomatic_quality: 20
trimmomatic_minlen: 50

# nanofilt is used for trimming MinION reads which requires a minimum quality

nanofilt_quality: 10

# -------------- IRMA assembly -------------- #

# IRMA can assemble either Illumina or MinION data
# important that the correct module is specified here
# either "FLU-avian" or "FLU-minion"

irma_module: FLU-avian


# -------------- SAN query parameters -------------- #

# these parameters allow the pipeline to lookup a SAN and retrive information
# note: the api_key should not be checked into github
# this can be obtained from Matt or Ivano

san_query_endpoint: "https://mars.csiro.au/xseqcore-api/sanquery/jobdetails"

api_key: ""

blast_email: ""

## -------------- Location of databases -------------- ##


blast_nt: "/data/bioref/blast/ncbi/nt"
blast_nr: "/data/bioref/blast/ncbi/nr"
blast_flu: "/flush5/nea040/AIV_pipeline/db/influenza_A_genbank.fasta"

diamond_nr: "/data/bioref/diamond_db/nr.dmnd"

cleavage_sites: "/flush5/nea040/AIV_pipeline/db/extended_info.csv"


## -------------- Pipline install location -------------- ##

# This needs to be changed to where the pipeline is installed

program_dir: "/datasets/work/aahl-pdngs/work/pipelines/AIV_pipeline"

